clear;
clc;
close;
[codeArray] = accessFile('dots.nc');
[codeArray] = deleteComments(codeArray);
[line] = segregateLines(codeArray);
[Z,height,neutral,depth] = getZValues(line);
[plungeRate,feedRate] = getFValues(line);
[line] = completeLines(line);
[block] = generateBlocks(line,height,depth);
[distance,globalConnectionList] = calculateDistances(block);
[distance] = cleanDistanceMatrix(distance,block);
[blockConnections] = blockDistance(block,distance);
[bestSequences,trials] = optimize(1,300,25,10,5,blockConnections,block,distance,plungeRate,feedRate,height,neutral,depth);
[finalSequence,finalCost,actualConnections] = rectify(trials,bestSequences,blockConnections,block,distance,plungeRate,feedRate,height,neutral,depth);
[finalCode] = translator(finalSequence,actualConnections,block,line,plungeRate,feedRate,height,neutral);
file = fopen('betterdot.nc', 'w');
fprintf(file, finalCode);
fclose('all');